### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by HashedViking** [lshug/first-order-model-tf#3]
`build.py` fails at  `generator_tflite = generator_converter.convert()`

Error disappears adding:
```
generator_converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```
~~But that probably causes `testlite.py` to fail.~~
check #2 comments

Full output of `build.py`:
```
Building
2021-04-02 00:52:54.522699: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-02 00:52:54.522905: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-02 00:53:02.259372: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2021-04-02 00:53:54.463387: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored output_format.
2021-04-02 00:53:54.463405: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored drop_control_dependency.
2021-04-02 00:53:54.463412: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:325] Ignored change_concat_input_ranges.
2021-04-02 00:53:54.465174: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: saved_models/vox/kp_detector
2021-04-02 00:53:54.490987: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2021-04-02 00:53:54.491013: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: saved_models/vox/kp_detector
2021-04-02 00:53:54.586574: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-04-02 00:53:54.607108: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-04-02 00:53:54.838562: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: saved_models/vox/kp_detector
2021-04-02 00:53:54.937545: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 472375 microseconds.
2021-04-02 00:53:55.382793: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-04-02 00:54:04.149392: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored output_format.
2021-04-02 00:54:04.149406: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored drop_control_dependency.
2021-04-02 00:54:04.149410: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:325] Ignored change_concat_input_ranges.
2021-04-02 00:54:04.149530: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: saved_models/vox/generator
2021-04-02 00:54:04.201645: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2021-04-02 00:54:04.201668: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: saved_models/vox/generator
2021-04-02 00:54:04.473078: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-04-02 00:54:05.033412: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: saved_models/vox/generator
2021-04-02 00:54:05.263320: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 1113790 microseconds.
loc(callsite(callsite("model_1/kp_to_gaussian/pow@__inference___call___19628" at "StatefulPartitionedCall@__inference_signature_wrapper_19975") at "StatefulPartitionedCall")): error: 'tf.Pow' op is neither a custom op nor a flex op
loc(callsite(callsite("model_1/kp_to_gaussian_1/pow@__inference___call___19628" at "StatefulPartitionedCall@__inference_signature_wrapper_19975") at "StatefulPartitionedCall")): error: 'tf.Pow' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Pow {device = ""}
Traceback (most recent call last):
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 210, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc(callsite(callsite("model_1/kp_to_gaussian/pow@__inference___call___19628" at "StatefulPartitionedCall@__inference_signature_wrapper_19975") at "StatefulPartitionedCall")): 'tf.Pow' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model_1/kp_to_gaussian_1/pow@__inference___call___19628" at "StatefulPartitionedCall@__inference_signature_wrapper_19975") at "StatefulPartitionedCall")): 'tf.Pow' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Pow {device = ""}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/SERG/development/first-order-model/first-order-model-tf-fork/build.py", line 60, in <module>
    build(checkpoint_path,config_path,output_name)
  File "/Users/SERG/development/first-order-model/first-order-model-tf-fork/build.py", line 40, in build
    generator_tflite = generator_converter.convert()
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 739, in convert
    result = _convert_saved_model(**converter_kwargs)
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 632, in convert_saved_model
    data = toco_convert_protos(
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(callsite(callsite("model_1/kp_to_gaussian/pow@__inference___call___19628" at "StatefulPartitionedCall@__inference_signature_wrapper_19975") at "StatefulPartitionedCall")): 'tf.Pow' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model_1/kp_to_gaussian_1/pow@__inference___call___19628" at "StatefulPartitionedCall@__inference_signature_wrapper_19975") at "StatefulPartitionedCall")): 'tf.Pow' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Pow {device = ""}
```

**Comment by lshug** [comment]
Looks like I went overboard in removing reshape hacks I didn't think were necessary. Fixed that stuff now. Can you try again and confirm it works?

Also, adding tf.lite.OpsSet.SELECT_TF_OPS should not be necessary. As is, the lite model will only use tf lite ops. The issue was with tfl:MulOp not being able to be translated from tf::MulOp if the tensor rank is >4 and the tensors need broadcasting. Now the code reshapes to a lower-rank tensor before doing multiplications and then changes the shapes back after multiplications.

**Comment by HashedViking** [comment]
~~Fails even with `tf.lite.OpsSet.SELECT_TF_OPS`~~
It does not matter as it fails earlier on `kp_detector_tflite = kp_detector_converter.convert()` as stacktrace says.
Build output:
```
Building
2021-04-02 12:56:08.257659: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-02 12:56:08.257942: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-02 12:56:19.063495: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2021-04-02 12:56:30.622428: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored output_format.
2021-04-02 12:56:30.622448: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored drop_control_dependency.
2021-04-02 12:56:30.622453: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:325] Ignored change_concat_input_ranges.
2021-04-02 12:56:30.623858: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: saved_models/vox/kp_detector
2021-04-02 12:56:30.658746: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2021-04-02 12:56:30.658776: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: saved_models/vox/kp_detector
2021-04-02 12:56:30.779738: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-04-02 12:56:30.807684: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-04-02 12:56:31.103520: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: saved_models/vox/kp_detector
2021-04-02 12:56:31.241560: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 617703 microseconds.
2021-04-02 12:56:31.809943: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_1@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): error: 'tf.StridedSlice' op is neither a custom op nor a flex op
loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_3@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): error: 'tf.StridedSlice' op is neither a custom op nor a flex op
loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_5@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): error: 'tf.StridedSlice' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
Traceback (most recent call last):
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 210, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_1@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_3@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_5@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/SERG/development/first-order-model/first-order-model-tf-main-d/build.py", line 54, in <module>
    build(checkpoint_path,config_path,output_name)
  File "/Users/SERG/development/first-order-model/first-order-model-tf-main-d/build.py", line 27, in build
    kp_detector_tflite = kp_detector_converter.convert()
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 739, in convert
    result = _convert_saved_model(**converter_kwargs)
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 632, in convert_saved_model
    data = toco_convert_protos(
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_1@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_3@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model/anti_alias_interpolation2d/strided_slice_5@__inference___call___6195" at "StatefulPartitionedCall@__inference_signature_wrapper_6330") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
```

**Edit:**
Adding the notorious `tf.lite.OpsSet.SELECT_TF_OPS` to `kp_detector_converter` fixes the problem
```
kp_detector_converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```

Now both `kp_detector_converter` and `generator_converter` fail without `tf.lite.OpsSet.SELECT_TF_OPS`

**Comment by lshug** [comment]
Looks like it's seeing TF::StridedSliceOp in AntiAliasInterpolation2d because of the ellipsis in [...,i] indexing for k and im in the call., when it's supposed to see the expression as normal slicing, with keeping everything from all dims except the last one, from which it should only keep values in ith channel. This is still weird, as it's building without problems on my end. I added a workaround. can you try again without SELECT_TF_OPS?

**Comment by HashedViking** [comment]
`kp_detector_converter` is fixed
`generator_converter` still needs `tf.lite.OpsSet.SELECT_TF_OPS`
Build output:
```
Building
2021-04-02 13:48:44.432913: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-02 13:48:44.433098: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-02 13:48:51.437221: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2021-04-02 13:48:59.044219: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored output_format.
2021-04-02 13:48:59.044234: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored drop_control_dependency.
2021-04-02 13:48:59.044238: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:325] Ignored change_concat_input_ranges.
2021-04-02 13:48:59.045204: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: saved_models/vox/kp_detector
2021-04-02 13:48:59.071151: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2021-04-02 13:48:59.071176: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: saved_models/vox/kp_detector
2021-04-02 13:48:59.157761: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-04-02 13:48:59.178660: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-04-02 13:48:59.403682: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: saved_models/vox/kp_detector
2021-04-02 13:48:59.511298: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 466094 microseconds.
2021-04-02 13:48:59.955967: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-04-02 13:49:26.608445: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored output_format.
2021-04-02 13:49:26.608460: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored drop_control_dependency.
2021-04-02 13:49:26.608463: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:325] Ignored change_concat_input_ranges.
2021-04-02 13:49:26.608579: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: saved_models/vox/generator
2021-04-02 13:49:26.660957: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2021-04-02 13:49:26.660978: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: saved_models/vox/generator
2021-04-02 13:49:26.914893: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2021-04-02 13:49:27.473568: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: saved_models/vox/generator
2021-04-02 13:49:27.689936: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 1081356 microseconds.
loc(callsite(callsite("model_1/deform/grid_sample/strided_slice_1@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): error: 'tf.StridedSlice' op is neither a custom op nor a flex op
loc(callsite(callsite("model_1/deform/grid_sample/strided_slice_2@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): error: 'tf.StridedSlice' op is neither a custom op nor a flex op
loc(callsite(callsite("model_1/grid_sample/strided_slice_1@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): error: 'tf.StridedSlice' op is neither a custom op nor a flex op
loc(callsite(callsite("model_1/grid_sample/strided_slice_2@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): error: 'tf.StridedSlice' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
Traceback (most recent call last):
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 210, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc(callsite(callsite("model_1/deform/grid_sample/strided_slice_1@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model_1/deform/grid_sample/strided_slice_2@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model_1/grid_sample/strided_slice_1@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model_1/grid_sample/strided_slice_2@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/SERG/development/first-order-model/first-order-model-tf-fork/build.py", line 62, in <module>
    build(checkpoint_path,config_path,output_name)
  File "/Users/SERG/development/first-order-model/first-order-model-tf-fork/build.py", line 41, in build
    generator_tflite = generator_converter.convert()
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 739, in convert
    result = _convert_saved_model(**converter_kwargs)
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 632, in convert_saved_model
    data = toco_convert_protos(
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(callsite(callsite("model_1/deform/grid_sample/strided_slice_1@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model_1/deform/grid_sample/strided_slice_2@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model_1/grid_sample/strided_slice_1@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("model_1/grid_sample/strided_slice_2@__inference___call___30722" at "StatefulPartitionedCall@__inference_signature_wrapper_31075") at "StatefulPartitionedCall")): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.StridedSlice {begin_mask = 0 : i64, device = "", ellipsis_mask = 1 : i64, end_mask = 0 : i64, new_axis_mask = 0 : i64, shrink_axis_mask = 2 : i64}
```

**Comment by lshug** [comment]
I've removed strided slicing from GridSample too. Let's hope no other tf::-only version-dependent op/dtype/shape combinations pop out. Can you try again?

**Comment by HashedViking** [comment]
Yeah, give me a moment

**Comment by HashedViking** [comment]
Nice! Everything works without `tf.lite.OpsSet.SELECT_TF_OPS`

**Comment by lshug** [comment]
Nice! If you encounter any other issues please ping me again.

**Comment by farazBhatti** [comment]
@lshug @HashedViking  I am still getting the same error

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 85, in <module>
    build(checkpoint_path, config_path, output_name, parser.module, parser.predictiononly, parser.tfjs, parser.jsquantize)
  File "build.py", line 51, in build
    generator_tflite = generator_converter.convert()
  File "/home/faraz/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 739, in convert
    result = _convert_saved_model(**converter_kwargs)
  File "/home/faraz/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 637, in convert_saved_model
    enable_mlir_converter=True)
  File "/home/faraz/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
`
on  line 
`        generator_tflite = generator_converter.convert()
`

Any thoughts?

**Comment by lshug** [comment]
@farazBhatti Can you try on python 3.8 with TensorFlow 2.5rc3? Please post the full output if it throws an error.

**Comment by farazBhatti** [comment]
@lshug  ok,sure
