### ISSUE TITLE
Testlite fails after update

### ISSUE THREAD

**Issue by HashedViking** [lshug/first-order-model-tf#4]
Hello, @lshug, I've tried to run [the updated version](https://github.com/lshug/first-order-model-tf/commit/ca0770848b8c4ee82581dff6391406055cb4211a) - but `testlite.py` failed (`build.py` is ok though)

`testlite.py` output:
```
2021-04-05 14:50:26.978736: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-05 14:50:26.979093: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-05 14:50:26.979896: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2021-04-05 14:50:26.979906: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
100%|██████████| 66/66 [00:18<00:00,  3.63it/s]
Traceback (most recent call last):
  File "/Users/SERG/development/first-order-model/first-order-model-tf-fork/testlite.py", line 108, in <module>
    predictions = animate(source_image, frames, generator, kp_detector, process_kp_driving, 4, parser.relative, parser.adapt_movement_scale)
  File "/Users/SERG/development/first-order-model/first-order-model-tf-fork/animate.py", line 35, in animate
    kp_driving, kp_driving_jacobian = process_kp_driving(
  File "/Users/SERG/development/first-order-model/first-order-model-tf-fork/testlite.py", line 94, in process_kp_driving
    process_kp_driving_interpreter.allocate_tensors()
  File "/Users/SERG/opt/anaconda3/envs/fom_tf/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 259, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (5280 != 20)Node number 5 (RESHAPE) failed to prepare.
```

**Comment by lshug** [comment]
This looks like an issue with tf.expand_dims being translated to TFL::ReshapeOp during model conversion with batch dimension getting mistakenly fixed to 1 and not resizing with resize_tensor_input. I'll change tf.expand_dims to equivalent tf.reshapes in a bit.

**Comment by lshug** [comment]
I've pushed the change. Can you try running testlite again?

**Comment by HashedViking** [comment]
It's working, and mouth animates better, but some shoulder artefacts appeared.

https://user-images.githubusercontent.com/6432677/113621553-6c221100-9664-11eb-9f2f-d396bbc41923.mp4

**Comment by HashedViking** [comment]
![source_2](https://user-images.githubusercontent.com/6432677/113621786-befbc880-9664-11eb-85c4-31b1ef15ba83.png)

https://user-images.githubusercontent.com/6432677/113621789-c15e2280-9664-11eb-9080-cb99b72d7bd6.mp4


https://user-images.githubusercontent.com/6432677/113621792-c1f6b900-9664-11eb-8192-8d1e590f104c.mp4


Original FOM result:

https://user-images.githubusercontent.com/6432677/113622451-b35cd180-9665-11eb-9b01-df36cae74dac.mp4

**Comment by lshug** [comment]
That's a pretty significant divergence. I'm gonna retrace intermediate outputs in both versions, see where it arises and fix it.

**Comment by lshug** [comment]
@HashedViking See #5
